param(
  [switch]$NonInteractive,
  [switch]$NoLaunch,
  [ValidateSet('mirror', 'default')]
  [string]$DownloadSource = 'mirror',
  [ValidateRange(30, 3600)]
  [int]$StepTimeoutSeconds = 900
)

$ErrorActionPreference = 'Stop'
if (-not $NonInteractive) {
  Add-Type -AssemblyName System.Windows.Forms
  Add-Type -AssemblyName System.Drawing
  [System.Windows.Forms.Application]::EnableVisualStyles()
}

$projectRoot = Split-Path -Parent $PSScriptRoot
$marker = Join-Path $projectRoot '.bilitoolkit-setup-complete'
$receipt = Join-Path $projectRoot 'node_modules\.bilitoolkit-setup-state'
$lockfile = Join-Path $projectRoot 'package-lock.json'
$devScript = Join-Path $PSScriptRoot 'run-windows-dev.ps1'
$script:cancelRequested = $false
$script:attempt = 0
$script:exitCode = 1
$form = $null
$originalFfmpegMirror = $env:FFMPEG_BINARIES_URL
$originalElectronMirror = $env:ELECTRON_MIRROR

function Test-DependenciesReady {
  foreach ($relativePath in @(
    'node_modules\.bin\vite.cmd',
    'node_modules\electron\dist\electron.exe',
    'node_modules\ffmpeg-static\ffmpeg.exe',
    'node_modules\better-sqlite3\build\Release\better_sqlite3.node'
  )) {
    if (-not (Test-Path -LiteralPath (Join-Path $projectRoot $relativePath) -PathType Leaf)) { return $false }
  }
  # Check every required locked package as well as the large binaries. Optional
  # platform-specific packages may legitimately be absent on Windows.
  & node.exe -e "const fs=require('fs'),p=require('path'),root=process.argv[1],lock=JSON.parse(fs.readFileSync(p.join(root,'package-lock.json'),'utf8'));for(const [name,entry] of Object.entries(lock.packages||{})){if(!name||entry.optional||entry.link)continue;try{const actual=JSON.parse(fs.readFileSync(p.join(root,name,'package.json'),'utf8'));if(actual.version!==entry.version)process.exit(1)}catch{process.exit(1)}}" $projectRoot
  return ($LASTEXITCODE -eq 0)
}

function Test-BuildReady {
  # dist-electron/preload.js is generated by Vite when development starts.
  foreach ($relativePath in @(
    'public\preloads\plugin-preload.cjs',
    'public\preloads\dialog-app-preload.cjs',
    'public\workers\task-plugin.worker.js',
    'public\recommended-plugins.json'
  )) {
    if (-not (Test-Path -LiteralPath (Join-Path $projectRoot $relativePath) -PathType Leaf)) { return $false }
  }
  return $true
}

function Get-SavedLockHash {
  # Keep a second receipt inside node_modules, so removing the root marker
  # cannot hide a lockfile change or trigger an unnecessary download.
  foreach ($path in @($receipt, $marker)) {
    if (Test-Path -LiteralPath $path) {
      return (Get-Content -LiteralPath $path -Raw).Trim()
    }
  }
  return ''
}

function Save-SetupState {
  Set-Content -LiteralPath $receipt -Value $currentLockHash -Encoding ASCII
  Set-Content -LiteralPath $marker -Value $currentLockHash -Encoding ASCII
}

function Start-DevelopmentApp {
  if ($NoLaunch) {
    Write-Output 'SETUP_READY: application launch skipped (-NoLaunch).'
    return
  }
  $arguments = '-NoProfile -ExecutionPolicy Bypass -File "' + $devScript + '"'
  Start-Process -FilePath 'powershell.exe' -ArgumentList $arguments -WorkingDirectory $projectRoot -WindowStyle Normal -ErrorAction Stop
}

function Set-DownloadSource([bool]$useMirror) {
  if ($useMirror) {
    $env:FFMPEG_BINARIES_URL = 'https://cdn.npmmirror.com/binaries/ffmpeg-static'
    $env:ELECTRON_MIRROR = 'https://npmmirror.com/mirrors/electron/'
  } else {
    # Default means the caller's original configuration, not deleting it.
    $env:FFMPEG_BINARIES_URL = $originalFfmpegMirror
    $env:ELECTRON_MIRROR = $originalElectronMirror
  }
}

function Test-OfficialElectronCache {
  if ($originalElectronMirror) { return $false }
  $electronVersion = (Get-Content -LiteralPath (Join-Path $projectRoot 'package.json') -Raw | ConvertFrom-Json).devDependencies.electron
  $cacheRoot = if ($env:ELECTRON_CACHE) { $env:ELECTRON_CACHE } else { Join-Path $env:LOCALAPPDATA 'electron\Cache' }
  if (-not (Test-Path -LiteralPath $cacheRoot)) { return $false }
  $archive = "electron-v$electronVersion-win32-x64.zip"
  return [bool](Get-ChildItem -LiteralPath $cacheRoot -Recurse -File -Filter $archive -ErrorAction SilentlyContinue | Where-Object { $_.Length -gt 0 } | Select-Object -First 1)
}

function Update-SetupLog([string]$stdoutPath, [string]$stderrPath) {
  if ($NonInteractive) { return }
  $lines = @()
  if (Test-Path -LiteralPath $stdoutPath) { $lines += @(Get-Content -LiteralPath $stdoutPath -Tail 10 -Encoding UTF8) }
  if (Test-Path -LiteralPath $stderrPath) { $lines += @(Get-Content -LiteralPath $stderrPath -Tail 10 -Encoding UTF8) }
  $logBox.Text = ($lines -join [Environment]::NewLine)
  $logBox.SelectionStart = $logBox.Text.Length
  $logBox.ScrollToCaret()
}

function Invoke-SetupStep([string]$title, [string]$command, [int]$number) {
  $script:attempt++
  $label = "第 $number/3 步：$title"
  if ($NonInteractive) { Write-Host $label } else {
    $status.Text = $label
    $logBox.Text = "正在运行：$command"
    $form.Refresh()
  }
  $stdoutPath = Join-Path $logDirectory "$($script:attempt)-step-$number.out.log"
  $stderrPath = Join-Path $logDirectory "$($script:attempt)-step-$number.err.log"
  $info = New-Object System.Diagnostics.ProcessStartInfo
  $info.FileName = $env:ComSpec
  $info.Arguments = '/d /s /c "' + $command + ' 1>"' + $stdoutPath + '" 2>"' + $stderrPath + '""'
  $info.WorkingDirectory = $projectRoot
  $info.UseShellExecute = $false
  $info.CreateNoWindow = $true
  $process = New-Object System.Diagnostics.Process
  $process.StartInfo = $info
  $watch = [System.Diagnostics.Stopwatch]::StartNew()
  $started = $false
  try {
    $started = $process.Start()
    while (-not $process.HasExited) {
      if (-not $NonInteractive) { [System.Windows.Forms.Application]::DoEvents() }
      Update-SetupLog $stdoutPath $stderrPath
      if ($script:cancelRequested) { return $false }
      if ($watch.Elapsed.TotalSeconds -ge $StepTimeoutSeconds) {
        throw "本步骤超过 $StepTimeoutSeconds 秒，已停止。日志：$logDirectory"
      }
      Start-Sleep -Milliseconds 300
      $process.Refresh()
    }
    $process.WaitForExit()
    Update-SetupLog $stdoutPath $stderrPath
    Write-Host ("STEP_RESULT: step={0}, attempt={1}, exit={2}, seconds={3:N1}, logs={4}" -f $number, $script:attempt, $process.ExitCode, $watch.Elapsed.TotalSeconds, $logDirectory)
    return ($process.ExitCode -eq 0)
  } finally {
    if ($started -and -not $process.HasExited) { & taskkill.exe /PID $process.Id /T /F *> $null }
    $process.Dispose()
  }
}

try {
  if (-not (Get-Command node.exe -ErrorAction SilentlyContinue) -or -not (Get-Command npm.cmd -ErrorAction SilentlyContinue)) {
    throw "源码版需要先安装 Node.js。普通用户可直接下载安装包：`nhttps://github.com/hzhilong/bilitoolkit/releases/latest"
  }
  & node.exe -e "const v=process.versions.node.split('.').map(Number);process.exit((v[0]===20&&v[1]>=19)||(v[0]===22&&v[1]>=12)||v[0]>22?0:1)"
  if ($LASTEXITCODE -ne 0) { throw "需要 Node.js 20.19+ 或 22.12+。当前版本：$(& node.exe --version)" }
  $currentLockHash = (Get-FileHash -LiteralPath $lockfile -Algorithm SHA256).Hash
  $dependenciesReady = Test-DependenciesReady
  $savedLockHash = Get-SavedLockHash
  $reuseDependencies = $dependenciesReady -and ($savedLockHash -eq $currentLockHash)
  if ($reuseDependencies -and (Test-BuildReady)) {
    Save-SetupState
    Write-Host 'REUSE_READY: dependencies and build resources unchanged; no installation.'
    Start-DevelopmentApp
    $script:exitCode = 0
  } else {
    $useMirror = $DownloadSource -eq 'mirror'
    if (-not $NonInteractive) {
      $form = New-Object System.Windows.Forms.Form
      $form.Text = '哔哩工具姬 · 安装与修复'
      $form.ClientSize = New-Object System.Drawing.Size(680, 420)
      $form.StartPosition = 'CenterScreen'
      $form.FormBorderStyle = 'FixedDialog'
      $form.MaximizeBox = $false
      $form.MinimizeBox = $false
      $form.ControlBox = $false
      $form.Font = New-Object System.Drawing.Font('Microsoft YaHei UI', 10)
      $status = New-Object System.Windows.Forms.Label
      $status.Location = New-Object System.Drawing.Point(20, 20)
      $status.Size = New-Object System.Drawing.Size(640, 32)
      $status.Text = '选择下载方式，然后点击“开始安装”。'
      $form.Controls.Add($status)
      $hint = New-Object System.Windows.Forms.Label
      $hint.Location = New-Object System.Drawing.Point(20, 54)
      $hint.Size = New-Object System.Drawing.Size(640, 42)
      $hint.Text = '首次安装需要联网。进度条表示仍在处理，不代表精确下载百分比。'
      $form.Controls.Add($hint)
      $mirror = New-Object System.Windows.Forms.CheckBox
      $mirror.Location = New-Object System.Drawing.Point(20, 98)
      $mirror.Size = New-Object System.Drawing.Size(640, 25)
      $mirror.Text = '使用国内镜像下载 Electron 和 FFmpeg（不改变 npm 全局配置）'
      $mirror.Checked = $useMirror -and -not (Test-OfficialElectronCache)
      $form.Controls.Add($mirror)
      $progress = New-Object System.Windows.Forms.ProgressBar
      $progress.Location = New-Object System.Drawing.Point(20, 130)
      $progress.Size = New-Object System.Drawing.Size(640, 20)
      $progress.Style = 'Blocks'
      $form.Controls.Add($progress)
      $logBox = New-Object System.Windows.Forms.TextBox
      $logBox.Location = New-Object System.Drawing.Point(20, 162)
      $logBox.Size = New-Object System.Drawing.Size(640, 196)
      $logBox.Multiline = $true
      $logBox.ReadOnly = $true
      $logBox.ScrollBars = 'Vertical'
      $logBox.Font = New-Object System.Drawing.Font('Consolas', 9)
      $form.Controls.Add($logBox)
      $start = New-Object System.Windows.Forms.Button
      $start.Location = New-Object System.Drawing.Point(430, 375)
      $start.Size = New-Object System.Drawing.Size(120, 28)
      $start.Text = '开始安装'
      $script:startRequested = $false
      $start.Add_Click({ $script:startRequested = $true })
      $form.Controls.Add($start)
      $cancel = New-Object System.Windows.Forms.Button
      $cancel.Location = New-Object System.Drawing.Point(560, 375)
      $cancel.Size = New-Object System.Drawing.Size(100, 28)
      $cancel.Text = '取消'
      $cancel.Add_Click({ $script:cancelRequested = $true })
      $form.Controls.Add($cancel)
      $form.Show()
      while (-not $script:startRequested -and -not $script:cancelRequested) {
        [System.Windows.Forms.Application]::DoEvents()
        Start-Sleep -Milliseconds 100
      }
      $useMirror = $mirror.Checked
      $mirror.Enabled = $false
      $start.Enabled = $false
      $progress.Style = 'Marquee'
      $progress.MarqueeAnimationSpeed = 25
    }
    if (-not $script:cancelRequested) {
      $logDirectory = Join-Path $projectRoot ('.bilitoolkit-setup-logs\' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + $PID)
      [void][System.IO.Directory]::CreateDirectory($logDirectory)
      # Invalidate both receipts before doing work: failed repair must not look ready.
      # A distinct state is safer than deleting existing files.
      foreach ($path in @($marker, $receipt)) {
        if (Test-Path -LiteralPath $path) { Set-Content -LiteralPath $path -Value 'incomplete' -Encoding ASCII }
      }
      $installed = $reuseDependencies
      if (-not $installed) {
        Set-DownloadSource $useMirror
        $installed = Invoke-SetupStep '安装依赖（包括 FFmpeg 和 Electron）' 'npm.cmd ci --prefer-offline --no-audit --no-fund --foreground-scripts' 1
        if (-not $installed -and -not $script:cancelRequested) {
          if (-not $NonInteractive) { $hint.Text = '依赖安装失败，切换下载地址重试一次；两次日志都会保留。' }
          Set-DownloadSource (-not $useMirror)
          $installed = Invoke-SetupStep '重试安装依赖' 'npm.cmd ci --prefer-offline --no-audit --no-fund --foreground-scripts' 1
        }
      } else {
        Write-Host 'REUSE_DEPENDENCIES: repairing build resources without npm ci.'
      }
      $built = $false
      $rebuilt = $false
      if ($installed -and -not $script:cancelRequested) { $built = Invoke-SetupStep '构建运行资源' 'npm.cmd run build:all' 2 }
      if ($installed -and $built -and -not $script:cancelRequested) { $rebuilt = Invoke-SetupStep '准备本机数据库模块' 'npm.cmd run rebuild:native' 3 }
      if ($installed -and $built -and $rebuilt -and -not $script:cancelRequested) {
        if (-not (Test-DependenciesReady) -or -not (Test-BuildReady)) { throw "安装命令已结束，但必需文件不完整。日志：$logDirectory" }
        Save-SetupState
        if ($form) { $form.Close() }
        try { Start-DevelopmentApp } catch { throw "安装已成功，但启动终端失败：$($_.Exception.Message)" }
        $script:exitCode = 0
      } elseif (-not $script:cancelRequested) {
        throw "安装或构建失败，未写入完成标记。请检查日志：$logDirectory"
      }
    }
  }
} catch {
  if ($NonInteractive) {
    [Console]::Error.WriteLine($_.Exception.Message)
  } else {
    if ($form -and $form.Visible -and -not $script:cancelRequested) {
      $status.Text = if ($_.Exception.Message -like '安装已成功*') { '安装成功，启动终端失败' } else { '安装或修复失败' }
      $hint.Text = '请查看下方错误，完整日志保存在项目的 .bilitoolkit-setup-logs 目录。'
      $logBox.AppendText([Environment]::NewLine + $_.Exception.Message)
      $logBox.SelectionStart = $logBox.Text.Length
      $logBox.ScrollToCaret()
      $progress.Style = 'Blocks'
      $progress.Value = 0
      $cancel.Text = '关闭'
      while ($form.Visible -and -not $script:cancelRequested) {
        [System.Windows.Forms.Application]::DoEvents()
        Start-Sleep -Milliseconds 100
      }
      $form.Close()
    } elseif (-not $script:cancelRequested) {
      [void][System.Windows.Forms.MessageBox]::Show($_.Exception.Message, '哔哩工具姬', 'OK', 'Error')
    }
  }
} finally {
  $env:FFMPEG_BINARIES_URL = $originalFfmpegMirror
  $env:ELECTRON_MIRROR = $originalElectronMirror
  if ($form) { $form.Dispose() }
}
exit $script:exitCode
